---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: knative-selfsigned-issuer
  labels:
    app.kubernetes.io/name: knative-serving
    networking.knative.dev/certificate-provider: cert-manager
spec:
  ca:
    secretName: knative-selfsigned-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-selfsigned-ca
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: knative-serving
    networking.knative.dev/certificate-provider: cert-manager
spec:
  secretName: knative-selfsigned-ca
  commonName: knative.dev
  usages:
    - server auth
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
